### ISSUE TITLE
提个建议，增加两个参数

### ISSUE THREAD

**Issue by lwb1978** [snowie2000/geoview#1]
建议增加两个参数：
第1个参数是设置后可在控制台输出时不输出任何错误信息，如果匹配到ip或域名就直接输出，没有匹配到或有其他错误就输出空字符串，这样方便sh采用 > 方式输出到文件。
第2个参数是设置后用-output输出文件时可以选择是覆盖还是追加的方式，调用时更灵活一些。

**Comment by lwb1978** [comment]
另外程序还有问题，就是不支持geosite:category-ai-chat-!cn这样的格式，当用这个参数时：-list "category-ai-chat-!cn" ，会输出：-bash: !cn: event not found，对！号进行转义-list "category-ai-chat-\!cn" 无输出

**Comment by snowie2000** [comment]
> 另外程序还有问题，就是不支持geosite:category-ai-chat-!cn这样的格式，当用这个参数时：-list "category-ai-chat-!cn" ，会输出：-bash: !cn: event not found，对！号进行转义-list "category-ai-chat-!cn" 无输出

对于!符号我是测试过的，例如geolocation-!cn，是可以正常输出的。你要确定geosite中存在这个tag

**Comment by snowie2000** [comment]
> 建议增加两个参数： 第1个参数是设置后可在控制台输出时不输出任何错误信息，如果匹配到ip或域名就直接输出，没有匹配到或有其他错误就输出空字符串，这样方便sh采用 > 方式输出到文件。 第2个参数是设置后用-output输出文件时可以选择是覆盖还是追加的方式，调用时更灵活一些。

由于程序本来就支持一次性输出多个地区，所以没有追加的必要。没有匹配到时是不会报错的，只会在参数错误或者文件不存在时报错

**Comment by lwb1978** [comment]
> > 建议增加两个参数： 第1个参数是设置后可在控制台输出时不输出任何错误信息，如果匹配到ip或域名就直接输出，没有匹配到或有其他错误就输出空字符串，这样方便sh采用 > 方式输出到文件。 第2个参数是设置后用-output输出文件时可以选择是覆盖还是追加的方式，调用时更灵活一些。
> 
> 由于程序本来就支持一次性输出多个地区，所以没有追加的必要。没有匹配到时是不会报错的，只会在参数错误或者文件不存在时报错

在实际调用时并没有你说的这么简单，如果我在处理pw的列表时不单要处理geoip/geosite的输出，还要处理手动添加的ip和域名，如果你的geoview不能追加就只能先输出，再追加手动添加的ip和域名，否则就得处理多个零散的文件，效率不高。

**Comment by snowie2000** [comment]
可以，这个没问题。你先用shell管道模拟一下。

**Comment by snowie2000** [comment]
> 控制台输出的话如果geoip没有找到项目会输出：Error: no entry is generated，建议不输出这个，直接输出空字符串即可。

我可以不输出错误，但这是没有意义的，因为出现了无效tag的情况xray和sing根本无法启动……

**Comment by lwb1978** [comment]
另外你-list后面参数的引号没做处理，估计引号也被当成参数了，比如我写成：
-list "category-ai-chat-\!cn" 则没有输出，必须写成 -list category-ai-chat-\!cn 这样才返回结果。

**Comment by snowie2000** [comment]
> 另外你-list后面参数的引号没做处理，估计引号也被当成参数了，比如我写成： -list "category-ai-chat-!cn" 则没有输出，必须写成 -list category-ai-chat-!cn 这样才返回结果。

引号是不需要处理的，go在读取参数时会自动处理并移除引号，把引号内的文字当做一个完整的参数

**Comment by snowie2000** [comment]
这是由于bash的history expansion导致的，你关掉就可以了 `set +H`

**Comment by snowie2000** [comment]
一开始测试时，我是在Windows上进行的，cmd没有这个功能，所以没有发现。在linux下的情况稍有不同，你需要调整一下

**Comment by snowie2000** [comment]
@lwb1978 已经发布了新的版本，编译好的程序可以在releases中下载到。

错误信息依然保留，但放到了stderr中，你用管道命令也不会被污染到。你也可以用append=true来指定追加而不是覆盖。程序会自动处理换行问题。

**Comment by lwb1978** [comment]
好的，晚上下班回去测试

**Comment by snowie2000** [comment]
0.0.3版本发布，参数做了调整，原来的action改为type，新增了新的action参数，支持extract和convert

convert支持从geo文件转换成sing-box的新的ruleset规则。规则格式由文件扩展名决定，json格式支持合并规则。

**Comment by lwb1978** [comment]
0.0.3怎么突然这么大了啊，10M，这体积赶上xray了

**Comment by snowie2000** [comment]
依赖了singbox的部分代码，singbox依赖了很多东西

**Comment by snowie2000** [comment]
要减小体积只能把它的代码直接提取出来才行

**Comment by lwb1978** [comment]
这样的话我可能不敢往pw上添加，毕竟pw所有者是小肉鸡，添加新的功能特别是组件的话需要征得他的同意，如果是体积小些我就敢直接做主了，体积太大的话我担心最后会被revert

**Comment by snowie2000** [comment]
所以做成可选依赖呀，要扒代码出来还是有些麻烦的。

**Comment by snowie2000** [comment]
[geoview.zip](https://github.com/user-attachments/files/17732965/geoview.zip)
@lwb1978 试试这个，我把代码摘出来了，然后去掉了符号，现在只有4M了

**Comment by snowie2000** [comment]
下个版本我会精简输出的ip范围为最简集合

**Comment by snowie2000** [comment]
0.0.5版本，降低了内存的使用，理论上速度应该比之前的更快一些

**Comment by snowie2000** [comment]
我发现xray使用的geoip和geosite格式用的是protobuf格式，singbox用的是maxmind格式，在速度上比xray的都要快得多，内存占用也要小很多，所以开启singbox并不会占用很多内存，但开启xray就会
