### ISSUE TITLE
讨论一下

### ISSUE THREAD

**Issue by lwb1978** [snowie2000/geoview#2]
-regex具体怎么使用呢？

**Comment by snowie2000** [comment]
geosite中有很多种不同规则，dnsmasq不支持正则，所以默认我把正则的规则屏蔽了。regex开关可以把正则输出来

**Comment by snowie2000** [comment]
确实是少传了文件，已经补上了，不好意思~

**Comment by snowie2000** [comment]
good to know, good to go.

**Comment by snowie2000** [comment]
其实我不是很明白为什么要同时生成gfw列表和中国域名列表。如果用了中国域名列表那不就是绕过cn模式了？
如果用gfw列表，那不再列表中的不是本来就是直连吗？为什么还需要中国列表？

我看了下我这边gfw列表是两个300k+的文件，并不大

**Comment by snowie2000** [comment]
我对openwrt的编译不是很熟悉，go肯定是支持mips的。

**Comment by snowie2000** [comment]
我忘了还有nft了

另外什么情况下会使用中国域名列表？

**Comment by snowie2000** [comment]
中国以外不是一般用chnroute嘛？

**Comment by snowie2000** [comment]
明白了，但gfw和cn列表似乎没有一起用的场景吧

**Comment by snowie2000** [comment]
我不会写makefile……应该是我的makefile写的不对，我需要去模仿下他们的

**Comment by snowie2000** [comment]
但pw不是一直都声称强制依赖dnsmasq吗，好像还把smartdns模式都改没了。现在又回过头去用回来了

**Comment by snowie2000** [comment]
我一直都用adguard配合dnsmasq作为它的上游……

**Comment by snowie2000** [comment]
这个是不包含调试符号的意思，不影响

**Comment by snowie2000** [comment]
我看了下xray和singbox的makefile，singbox对mips没有任何额外处理，xray实际上也没有，它只是检查GOARCH是否包含mips，然后会额外编译一个softfloat版本出来，对原有的编译没有作出任何修改。

你可以提供编译不通过时的错误日志吗？

**Comment by snowie2000** [comment]
arm的toolchain我是自己编译好的，如果都是action的话，那只能改成V=s显示详细信息去看了。

加上no-mips16是不是就不会编译mips相关的版本了？

**Comment by snowie2000** [comment]
我搜索了下，貌似v2ray之类也存在相同的问题，也是用no-mips16来规避的
https://github.com/fw876/helloworld/issues/1283

**Comment by snowie2000** [comment]
https://github.com/openwrt/packages/blob/3f35e9c06566af1783ced236ea31f05b68c5a823/net/overture/Makefile#L17

确实在一些go的项目中都看到了这个flag，但我不知道是什么意思。。。

**Comment by snowie2000** [comment]
0.0.7版本新增了lowmem参数。
使用这个参数可以避免将整个geoip.dat读入内存中，只会读取list中的国家，并且一次只读取一个。可以大大减少内存占用。

开启前，内存占用可以达到50-70M，开启后可以控制在30M左右（使用最大的US列表），如果是别的国家则可以低至10M以内。

**Comment by snowie2000** [comment]
> 如启用后us会慢几秒钟吗？

理论上会慢一些，但实际上我测试发现是……快不少……

> root@xx# time ./geoview -input geoip.dat -list us -output us.txt
> 
> real    0m1.948s
> user    0m1.266s
> sys     0m2.250s
> root@xx# time ./geoview -input geoip.dat -list us -output us.txt
> 
> real    0m2.114s
> user    0m1.234s
> sys     0m2.422s
> root@xx# time ./geoview -input geoip.dat -list us -output us.txt -lowmem=true
> 
> real    0m1.127s
> user    0m1.031s
> sys     0m0.859s
> root@xx# time ./geoview -input geoip.dat -list us -output us.txt -lowmem=true
> 
> real    0m1.264s
> user    0m0.844s
> sys     0m1.313s

**Comment by snowie2000** [comment]
不幸的是……会的。go自带的flag解析器不允许传递未知的flag进去……

**Comment by snowie2000** [comment]
你打算怎么解决参数不兼容的问题呢

**Comment by snowie2000** [comment]
[gv.zip](https://github.com/user-attachments/files/18010308/gv.zip)
0.0.7

**Comment by snowie2000** [comment]
可以通过读取opkg中的版本号

**Comment by snowie2000** [comment]
大小是一样的，给你的版本没去符号导致的。

**Comment by snowie2000** [comment]
不支持，因为那个本来占用就非常低，完全不需要优化。

当然你传了也不会报错

**Comment by snowie2000** [comment]
已经更新了0.0.8版本，添加了`-version`标记可以打印版本号
新版本开始可以忽略未知flag并继续正常执行，不会打印任何错误信息。但在未知flag后的命令行将被忽略
例如
`geoview -input geoip.dat -list cn -test`可以正常工作
但
`geoview -test -input geoip.dat -list cn`不可以

**Comment by snowie2000** [comment]
> 可喜的是，小肉鸡已经认可这个项目，PW2也采用了我的代码，我下一步准备把黑、白名单几个列表也支持geo解析

恭喜。pw2现在还是小肉鸡自己维护吗？
