### ISSUE TITLE
递归依赖问题

### ISSUE THREAD

**Issue by lwb1978** [snowie2000/geoview#4]
这里发现了这个问题
https://github.com/xiaorouji/openwrt-passwall/issues/3555
应该是你的makefile编写的问题，我在网上找线索，大概修了一下，你得空跟进看是否还能优化一下makefile。
主要修改的地方:https://github.com/xiaorouji/openwrt-passwall-packages/blob/cbd28a9ac0dddbd683c15e5555146594f314feec/v2ray-geoview/Makefile#L35

**Comment by snowie2000** [comment]
我是按照frpc的makefile写的，我也不太懂怎么写。
另外递归依赖不就是A依赖B，B依赖A吗？但geoview好像不依赖任何别的组件吧

**Comment by snowie2000** [comment]
makefile模版来源： https://github.com/kuoruan/openwrt-frp/blob/master/Makefile
